import type { NextPage } from 'next';
import Head from 'next/head';
import Tela from './tela';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Telas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Tela />
      </main>
    </div>
  );
};

export default Home;
